# @package _group_

common:
  fp16: true
  log_format: json
  log_interval: 100
  tensorboard_logdir: /home2/cwzhang98/project/MYST/audio_cif_pt_log

checkpoint:
  save_dir: /home2/cwzhang98/project/MYST/checkpoint
  restore_file: /home2/cwzhang98/project/MYST/checkpoint/checkpoint_last.pt
  no_epoch_checkpoints: true
  best_checkpoint_metric: loss
  patience: 10

task:
  _name: audio_finetuning
  data: ???
  normalize: false
  labels: pho
  enable_padding: true
  src_lang_tag: <lang:en>

dataset:
  num_workers: 8
  max_tokens: 5000000
  skip_invalid_size_inputs_valid_test: true
  valid_subset: dev_clean,dev_other
  update_epoch_batch_itr: false

distributed_training:
  ddp_backend: legacy_ddp
  distributed_world_size: 2

criterion:
  _name: label_smoothed_cross_entropy_with_ctc_with_qua
  report_accuracy: true
  ctc_weight: 0.5
  label_smoothing: 0.1

optimization:
  max_update: 500000
  clip_norm: 10.0
  lr: [1e-4]
  sentence_avg: true
  update_freq: [2]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-08

lr_scheduler:
  _name: inverse_sqrt
  warmup_updates: 4000

model:
  _name: wav2vec_ctc
  w2v_path: ???
  apply_mask: true
  mask_prob: 0.5
  no_mask_overlap: true
  mask_min_space: 10
  mask_dropout: 0.2
  mask_channel_prob: 0.1
  mask_channel_length: 10
  no_mask_channel_overlap: true
  mask_channel_min_space: 10
  dropout: 0.1
  activation_dropout: 0.0 # if set, asr performance will drop drastically
  feature_grad_mult: 0.0
  freeze_finetune_updates: 0
  weight_predictor_stop_gradient: true
  use_attention: true
  cif_attention_dropout: 0.1
  beta: 1.0
  ctc_joint_training: true
  shared_proj: true
  sub_sampler: true
