common:
  fp16: true
  log_format: json
  log_interval: 100
  tensorboard_logdir: ???

checkpoint:
  save_dir: ???
  restore_file: ???
  # save_interval_updates: 1000
  # save_interval: 1
  keep_last_epochs: 15
  # keep_interval_updates: 15
  # keep_best_checkpoints: 10
  best_checkpoint_metric: bleu
  maximize_best_checkpoint_metric: true
  patience: 10

task:
  _name: speech_to_text_cif_muti_contrast
  data: ???
  config_yaml: ???
  eval_bleu: true
  eval_bleu_detok: moses
  eval_tokenized_bleu: false
  eval_bleu_bpe: sentencepiece
  eval_bleu_args: '{"beam": 5, "prefix_size": 1, "lenpen": 0.6}'
  eval_bleu_print_samples: true
  use_joint_dict: false

criterion:
  _name: label_smoothed_cross_entropy_with_mt_multitask_contrastive
  label_smoothing: 0.1
  report_accuracy: true
  ignore_prefix_size: 1
  use_jsd: true
  contrast_granularity: coarse
  contrast_level: low
  contrastive_temperature: 0.02
  contrastive_weight: 1.0

model:
  _name: s2t_transformer_with_cif_contrast
  w2v_model_path: ???
  freeze_w2v: true
  activation_fn: relu
  dropout: 0.1
  attention_dropout: 0.1
  activation_dropout: 0.1
  encoder_layers: 6
  encoder_embed_dim: 512
  encoder_ffn_embed_dim: 2048
  encoder_attention_heads: 8
  encoder_normalize_before: true
  no_positional_embeddings: false
  encoder_learned_pos: false
  decoder_layers: 6
  decoder_embed_dim: 512
  decoder_ffn_embed_dim: 2048
  decoder_attention_heads: 8
  decoder_normalize_before: true
  share_decoder_input_output_embed: true
  layernorm_embedding: true
  no_scale_embedding: false
  ablation_type: w2v_transformer

dataset:
  num_workers: 32
  max_tokens: 5000000
  train_subset: train_st
  valid_subset: dev_st
  update_epoch_batch_itr: false
  skip_invalid_size_inputs_valid_test: true
  batch_size: 200

distributed_training:
  ddp_backend: legacy_ddp # same as legacy_ddp
  distributed_world_size: 1

optimization:
  max_update: 500000
  clip_norm: 10.0
  lr: [1e-4]
  sentence_avg: true
  update_freq: [2]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-08

lr_scheduler:
  _name: inverse_sqrt
  warmup_updates: 25_000
